import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { supabase } from "../supabase";
import Fv from "../components/Fv";
import Favorite from "../components/Favorite";

export default function Home({products}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Список товаров</h1>
        <ul style={{display:"flex", listStyle:"none", gap:"20px"}}>
          {
            products.map((el) => (
              <li key={el.id} style={{
                width:"250px",
                height:"350px",
                border:"1px solid gray",
                background:"white",
                color:"black",
                display:"flex",
                justifyContent:"space-between",
                padding:"10px"
                }}>
                <h2>{el.title}</h2>
                <Fv id={el.id}/>
                {/* <Favorite id={el.id}/> */}
              </li>
            
            ))
          }
        </ul>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const { data } = await supabase.from("products").select("id, title");

  return {
    props: {
      products: data
    },
  };
}
